#!/usr/bin/env bash
# isuenv が振ったホストの private IP を hosts.generated.mk に書き出す。
#
# public IP はグローバルIPが変わるたびに `isuenv ssh` で貼り直されるが、
# private IP はインスタンスを作り直すまで変わらない。
# ベンチのターゲット、決済サーバーのURL、アプリ→DBの接続先はこの private IP を使う。
#
# usage: ./tools/setup/gen-hosts.sh
set -euo pipefail
# isuenv の ssh 設定は known_hosts を持たないので、毎回出る "Permanently added" 警告を黙らせる
ssh() { command ssh -o LogLevel=ERROR "$@"; }
scp() { command scp -o LogLevel=ERROR "$@"; }
export RSYNC_RSH="ssh -o LogLevel=ERROR"

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$ROOT/hosts.generated.mk"

HOSTS=()
while IFS= read -r h; do
  [ -n "$h" ] && HOSTS+=("$h")
done < <(awk '/^Host isucon14-/ {print $2}' ~/.ssh/isuenv_config)

if [ "${#HOSTS[@]}" -eq 0 ]; then
  echo "no isuenv hosts found in ~/.ssh/isuenv_config — 先に isuenv up を実行してください" >&2
  exit 1
fi

{
  echo "# Generated by tools/setup/gen-hosts.sh. DO NOT EDIT."
  echo "# $(date '+%Y-%m-%d %H:%M:%S')"
  last=""
  for h in "${HOSTS[@]}"; do
    n="${h##*-}"
    ip=$(ssh -o ConnectTimeout=10 "$h" 'hostname -I | awk "{print \$1}"' 2>/dev/null || echo "")
    [ -z "$ip" ] && { echo "# $h: unreachable" ; continue ; }
    if [ "$n" -le 3 ]; then
      echo "ISU${n}_IP := $ip"
    else
      # isuenv の --bench / --bench-instance-type はベンチノードを競技ノードの次の番号で作る
      echo "BENCH := $h"
      echo "BENCH_IP := $ip"
    fi
    last="$h"
  done
} > "$OUT"

cat "$OUT"
